/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrimitivesRouteImport } from './routes/primitives'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrimitivesIndexRouteImport } from './routes/primitives.index'

const PrimitivesRoute = PrimitivesRouteImport.update({
  id: '/primitives',
  path: '/primitives',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimitivesIndexRoute = PrimitivesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrimitivesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/primitives': typeof PrimitivesRouteWithChildren
  '/primitives/': typeof PrimitivesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/primitives': typeof PrimitivesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/primitives': typeof PrimitivesRouteWithChildren
  '/primitives/': typeof PrimitivesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/primitives' | '/primitives/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/primitives'
  id: '__root__' | '/' | '/dashboard' | '/primitives' | '/primitives/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PrimitivesRoute: typeof PrimitivesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/primitives': {
      id: '/primitives'
      path: '/primitives'
      fullPath: '/primitives'
      preLoaderRoute: typeof PrimitivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primitives/': {
      id: '/primitives/'
      path: '/'
      fullPath: '/primitives/'
      preLoaderRoute: typeof PrimitivesIndexRouteImport
      parentRoute: typeof PrimitivesRoute
    }
  }
}

interface PrimitivesRouteChildren {
  PrimitivesIndexRoute: typeof PrimitivesIndexRoute
}

const PrimitivesRouteChildren: PrimitivesRouteChildren = {
  PrimitivesIndexRoute: PrimitivesIndexRoute,
}

const PrimitivesRouteWithChildren = PrimitivesRoute._addFileChildren(
  PrimitivesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PrimitivesRoute: PrimitivesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
